/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }]

  // But you can create a sidebar manually
  tutorialSidebar: [
    "why-use-renegade",
    {
      type: "category",
      label: "Integration Quickstart",
      collapsed: false,
      collapsible: false,
      link: {
        type: "doc",
        id: "integration-quickstart/intro",
      },
      items: [
        "integration-quickstart/direct-matches",
        "integration-quickstart/solver-rfqs",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      collapsible: false,
      items: [
        "concepts/dark-pool-explainer",
        "concepts/mpc-explainer",
        "concepts/mpc-zkp",
        "concepts/privacy",
      ],
    },
    {
      type: "category",
      label: "SDK Guide",
      collapsed: false,
      collapsible: false,
      link: {
        type: "doc",
        id: "sdk/intro",
      },
        items: [
            {
              type: "category",
              label: "Contract addresses and API endpoints",
              collapsed: false,
              collapsible: false,
              link: {
                type: "doc",
                id: "sdk/addresses/v2",
              },
              items: [
                "sdk/addresses/v2",
                "sdk/addresses/v1",
                "sdk/addresses/price-reporter",
                "sdk/addresses/whitelisted-tokens",
              ],
            },
            {
              type: "category",
              label: "Rust SDK Reference",
              collapsible: false,
              collapsed: false,
              link: {
                type: "doc",
                id: "sdk/rust/reference",
              },
              items: [
                {
                  type: "html",
                  value: '<a href="/sdk/rust/renegade_sdk/" target="_blank" rel="noopener noreferrer">Cargo Docs ↗</a>',
                  defaultStyle: true,
                },
              ],
            },
            {
              type: "category",
              label: "TypeScript SDK Reference",
              collapsible: false,
              collapsed: false,
              link: {
                type: "doc",
                id: "sdk/typescript/reference",
              },
              items: [
                {
                  type: "html",
                  value: '<a href="/sdk/typescript/" target="_blank" rel="noopener noreferrer">Typedoc ↗</a>',
                  defaultStyle: true,
                },
              ],
            },
            {
              type: "category",
              label: "Golang SDK Reference",
              collapsible: false,
              collapsed: false,
              link: {
                type: "doc",
                id: "sdk/golang/reference",
              },
              items: [
                {
                  type: "html",
                  value: '<a href="/sdk/golang/" target="_blank" rel="noopener noreferrer">Golang Docs ↗</a>',
                  defaultStyle: true,
                },
              ],
            },
            {
              type: "category",
              label: "Python SDK Reference",
              collapsible: false,
              collapsed: false,
              link: {
                type: "doc",
                id: "sdk/python/reference",
              },
              items: [
                {
                  type: "html",
                  value: '<a href="/sdk/python/" target="_blank" rel="noopener noreferrer">Python Docs ↗</a>',
                  defaultStyle: true,
                },
              ],
            },
        ],
    },
    {
      type: "category",
      label: "APIs",
      collapsed: false,
      collapsible: false,
      items: [
        "apis/price-reporter",
      ],
    },
    "rate-limits",
    "fees",
  ],
}

module.exports = sidebars
