name: Renegade + Docs
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prettier Check (renegade.fi)
        working-directory: ./renegade.fi
        run: |
          npm ci
          npx prettier --check src/ --config ./.prettierrc
      - name: Prettier Check (docs.renegade.fi)
        working-directory: ./docs.renegade.fi
        run: |
          npm ci
          npx prettier --check src/ --config ./.prettierrc
